server {
    listen 80;

    # 1. React Static Pages
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 2. Forward API Requests to Live Render Backend
    location /api/ {
        proxy_pass https://schemedesk-backen.onrender.com/api/;
        proxy_ssl_server_name on;
        proxy_set_header Host schemedesk-backen.onrender.com;
    }
}